### ISSUE TITLE
(#200) Requires extended permission: read_stream'

### ISSUE THREAD

**Issue by limeless** [ajay-gandhi/fb-cli#4]
After I Manually instal the Github version of falafel (awesome work btw)
I dont know how I did this.

![screen shot 2015-02-04 at 11 02 59 pm](https://cloud.githubusercontent.com/assets/1501022/6042723/040d15f2-acc2-11e4-81fa-f9c29e7cea4b.png)

there is no way I can bring up the login.html at do/
is somewhere I did wrong?

**Comment by ajay-gandhi** [comment]
We are currently working on getting the app approved by Facebook. In the meantime, you won't be able to actually access any of your personal data. Sorry!
